# Caprover schema version
captainVersion: 4

# Parameters of the Caprover one-click app

caproverOneClickApp:

    # Title and description for one-click app gallery

    displayName: Passbolt
    description: Passbolt is a free and open source password manager that allows team members to store and share credentials securely.
    
    # Only mark true if the docker-compose is the official one provided by the app developer, or if it's from a trusted source

    isOfficial: true

    # Onboarding instructions

    instructions:

        # Configuration page (user sets variables here)

        start: |-
            
            ![Passbolt Logo](https://nbygyyaygsxxesvjjcwa.supabase.co/storage/v1/object/public/public/passbolt.png?t=2022-08-09T18%3A29%3A21.472Z)
            

            🌐 [Passbolt website](https://www.passbolt.com/)
            📘 [Help & docs](https://help.passbolt.com/)
            💻 [Source code](https://github.com/passbolt)

            **Passbolt** is a free and open source password manager that allows team members to store and share credentials securely.
            This is a copy of the official Caprover image.
            Enter your Passbolt configuration parameters and click on next. The app will be deployed for you.  It will take about 1-2 minutes for the process to finish.

            ❗**If you like this app**, consider [donating](https://help.passbolt.com/faq/contribute/financial-contribution) or switching to a [SaaS version](https://signup.passbolt.com/cloud/signup) to support developers.
        
        # Success page

        end: >-
            ✨✨ **Passbolt is deployed successfully**. 
            Wait for a couple minutes for it to set up, then access at [http://$$cap_appname.$$cap_root_domain](http://$$cap_appname.$$cap_root_domain) and enjoy! 
            IMPORTANT: It will take up to 2 minutes for Passbolt to be ready. Before that, you might see a 502 error page.
            
    # Link to app's documentation and Docker Hub

    documentation: Access docs at https://help.passbolt.com/ . Docker image is taken from https://hub.docker.com/r/passbolt/passbolt.

    # Variables to be configured by the user

    variables:
        - id: $$cap_db_root_pass
          label: Database Root Password
          defaultValue: rootpassword
        - id: $$cap_db_user
          label: Database Username
          defaultValue: passbolt
        - id: $$cap_db_pass
          label: Database Password
          defaultValue: password
        - id: $$cap_pb_version
          label: Passbolt Version
          defaultValue: 2.12.1-debian
          description: Check out their Docker page for the valid tags https://hub.docker.com/r/passbolt/passbolt/tags/
        - id: $$cap_url
          label: Passbolt URL
          description: "This is VERY IMPORTANT, if you won't use a custom domain (ex: km.yourdomain.com), after Passbolt is deployed you will need to go into the App Configs and update the ENV APP_FULL_BASE_URL with the external URL that CapRover assigned to your App, otherwhise it won't work"
          defaultValue: https://yourdomain.com
        - id: $$cap_email_host
          label: Email SMTP Server
          description: 'Host used as smtp server. More info: https://help.passbolt.com/configure/email/setup.'
          defaultValue: smtp.gmail.com
        - id: $$cap_email_port
          label: Email SMTP Port
          description: 'Port used with the smtp server. More info: https://help.passbolt.com/configure/email/setup'
          defaultValue: '587'
        - id: $$cap_email_user
          label: Email Username
          defaultValue: user@gmail.com
        - id: $$cap_email_pass
          label: Email Password
          defaultValue: password
        - id: $$cap_email_tls
          label: TLS Enabled
          defaultValue: 'true'
    
# Docker-compose definition

services:
    $$cap_appname-db:
        image: mariadb:10.3
        environment:
            MYSQL_ROOT_PASSWORD: $$cap_db_root_pass
            MYSQL_DATABASE: passbolt_oca
            MYSQL_USER: $$cap_db_user
            MYSQL_PASSWORD: $$cap_db_pass
        volumes:
            - $$cap_appname-db:/var/lib/mysql
    $$cap_appname-pb:
        image: passbolt/passbolt:$$cap_pb_version
        depends_on:
            - $$cap_appname-db
        environment:
            DATASOURCES_DEFAULT_HOST: srv-captain--$$cap_appname-db:3306
            DATASOURCES_DEFAULT_DATABASE: passbolt_oca
            DATASOURCES_DEFAULT_USERNAME: $$cap_db_user
            DATASOURCES_DEFAULT_PASSWORD: $$cap_db_pass
            APP_FULL_BASE_URL: $$cap_url
            EMAIL_TRANSPORT_DEFAULT_HOST: $$cap_email_host
            EMAIL_TRANSPORT_DEFAULT_PORT: $$cap_email_port
            EMAIL_TRANSPORT_DEFAULT_USERNAME: $$cap_email_user
            EMAIL_DEFAULT_FROM: $$cap_email_user
            EMAIL_TRANSPORT_DEFAULT_PASSWORD: $$cap_email_pass
            EMAIL_TRANSPORT_DEFAULT_TLS: $$cap_email_tls
        volumes:
            - $$cap_appname-gpg:/var/www/passbolt/config/gpg
            - $$cap_appname-images:/var/www/passbolt/webroot/img/public