# Caprover schema version
captainVersion: 4

# Parameters of the Caprover one-click app

caproverOneClickApp:

    # Title and description for one-click app gallery

    displayName: Akaunting
    description: Operations, Accounting - Akaunting is open-source, self-hosted accounting software for small businesses and freelancers.
    
    # Only mark true if the docker-compose is the official one provided by the app developer, or if it's from a trusted source

    isOfficial: true

    # Onboarding instructions

    instructions:

        # Configuration page (user sets variables here)

        start: |-

            🌐 [Akaunting website](https://akaunting.com/)
            📘 [Help & docs](https://akaunting.com/support)
            💻 [Source code](https://github.com/akaunting/akaunting)

            **Akaunting** is open-source, self-hosted accounting software for small businesses and freelancers.
            This is a copy of the official Caprover image.
            Enter your Akaunting configuration parameters and click on next. The app will be deployed for you.  It will take about 1-2 minutes for the process to finish.

            ❗**If you like this app**, consider [donating](https://patreon.com/akaunting) or switching to a [SaaS version](https://akaunting.com/plans) to support developers.
        
        # Success page

        end: >-
            ✨✨ **Akaunting is deployed successfully**. 
            Wait for a couple minutes for it to set up, then access at [http://$$cap_appname.$$cap_root_domain](http://$$cap_appname.$$cap_root_domain) and enjoy! 
            IMPORTANT: It will take up to 2 minutes for Akaunting to be ready. Before that, you might see a 502 error page.

    # Link to app's documentation and Docker Hub

    documentation: Access docs at https://akaunting.com/support .

    # Variables to be configured by the user

    variables:
        - id: $$cap_app_version
          label: Akaunting Version
          defaultValue: '2.1.8'
          description: Check out their docker page for the valid tags https://hub.docker.com/r/akaunting/akaunting/tags

        - id: $$cap_db_pass
          label: Database Password
          defaultValue: $$cap_gen_random_hex(16)

        - id: $$cap_db_prefix
          label: Database Prefix
          defaultValue: 'aka_'

        - id: $$cap_company_name
          label: Company Name
          description: OPTIONAL

        - id: $$cap_company_email
          label: Company Email
          description: OPTIONAL

        - id: $$cap_admin_email
          label: Admin Email
          defaultValue: 'admin@company.com'
          description: This will be your default login username

        - id: $$cap_admin_password
          label: Admin Password
          defaultValue: $$cap_gen_random_hex(16)
          description: This will be your default login password
    
# Docker-compose definition

services:
    
    $$cap_appname:
        depends_on:
            - $$cap_appname-db
        image: akaunting/akaunting:$$cap_app_version
        restart: always
        environment:
            APP_URL: http://$$cap_appname.$$cap_root_domain
            LOCALE: en-US
            AKAUNTING_SETUP: true
            DB_HOST: srv-captain--$$cap_appname-db
            DB_PORT: 3306
            DB_USERNAME: akaunting
            DB_DATABASE: akaunting
            DB_PASSWORD: $$cap_db_pass
            DB_PREFIX: $$cap_db_prefix
            COMPANY_NAME: $$cap_company_name
            COMPANY_EMAIL: $$cap_company_email
            ADMIN_EMAIL: $$cap_admin_email
            ADMIN_PASSWORD: $$cap_admin_password
        volumes:
            - $$cap_appname-data:/akaunting-data
            - $$cap_appname-modules:/akaunting-modules
    # Database
    $$cap_appname-db:
        image: mariadb:10.5.9
        volumes:
            - $$cap_appname-db:/var/lib/mysql/data
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: $$cap_db_pass
            MYSQL_USER: akaunting
            MYSQL_PASSWORD: $$cap_db_pass
            MYSQL_DATABASE: akaunting
        caproverExtra:
            notExposeAsWebApp: 'true'