captainVersion: 4
version: "2.3"
networks:
  main:
services:
  jitsu:
    container_name: jitsu
    image: jitsucom/jitsu
    environment:
      - REDIS_URL=$$cap_redis_url
      #Retroactive users recognition can affect RAM significant. Read more about the solution https://jitsu.com/docs/other-features/retroactive-user-recognition
      - USER_RECOGNITION_ENABLED=true
      - USER_RECOGNITION_REDIS_URL=srv-captain--redis://srv-captain--redis_users_recognition:6380
      - TERM=xterm-256color
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - ./compose-data/configurator/data/logs:/home/configurator/data/logs
      - ./compose-data/server/data/logs:/home/eventnative/data/logs
      - ./compose-data/server/data/logs/events:/home/eventnative/data/logs/events
      - /var/run/docker.sock:/var/run/docker.sock
      - workspace:/home/eventnative/data/airbyte
    restart: always
    ports:
      - "8000:8000"
    networks:
      - main
  redis:
    container_name: jitsu_redis
    image: redis:6.2.6-bullseye
    volumes:
      - ./compose-data/redis/data:/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -h localhost -p 6379 PING"]
      interval: 1s
      timeout: 30s
    networks:
      - main
  redis_users_recognition:
    container_name: jitsu_redis_users_recognition
    image: redis:6.2.6-bullseye
    volumes:
      - ./compose-data/redis_users_recognition/data:/data
      - ./compose-data/redis_users_recognition/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: always
    networks:
      - main

volumes:
  workspace:
    name: jitsu_workspace
caproverOneClickApp:
    variables:
        - id: '$$cap_redis_url'
          label: Redis URL
          defaultValue: 'srv-captain--redis://srv-captain--redis:6379'
          description: Redis URL
        - id: '$$cap_tz'
          label: Time Zone
          defaultValue: America/New_York
          description: Get yours from https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
          validRegex: '/.{1,}/'
    instructions:
        start: |-
            jitsu
        end: |-
            jitsu has been successfully deployed!
    displayName: jitsu
    isOfficial: true
    description: Data and search, Data pipeline - jitsu
    documentation: See 