# Caprover schema version
captainVersion: 4

# Parameters of the Caprover one-click app

caproverOneClickApp:

    # Title and description for one-click app gallery

    displayName: Apprise
    description: Apprise is a library for developers to send notifications to most of the popular notification services available
    
    # Only mark true if the docker-compose is the official one provided by the app developer, or if it's from a trusted source

    isOfficial: true

    # Onboarding instructions

    instructions:

        # Configuration page (user sets variables here)

        start: |-
            
            ![Apprise Logo](https://nbygyyaygsxxesvjjcwa.supabase.co/storage/v1/object/public/public/apprise.png?t=2022-08-11T14%3A15%3A01.533Z)
            

            🌐 [Apprise website](https://github.com/caronc/apprise)
            📘 [Help & docs](https://github.com/caronc/apprise/wiki)
            💻 [Source code](https://github.com/caronc/apprise/)

            **Apprise** is a library for developers to send notifications to most of the popular notification services available. This includes Telegram, Discord, Slack, Amazon SNS, Gotify, and others.
            This is a copy of the official Caprover image.
            Enter your Apprise configuration parameters and click on next. The app will be deployed for you.  It will take about 1-2 minutes for the process to finish.
            
            ❗**If you like this app**, consider [donating](https://help.passbolt.com/faq/contribute/financial-contribution) or switching to a [SaaS version](https://signup.passbolt.com/cloud/signup) to support developers.
        
        # Success page

        end: >-
            ✨✨ **Apprise is deployed successfully**. 
            Wait for a couple minutes for it to set up, then access at [http://$$cap_appname.$$cap_root_domain](http://$$cap_appname.$$cap_root_domain) and enjoy!

    # Link to app's documentation and Docker Hub

    documentation: Access docs at https://github.com/caronc/apprise/wiki . Image is taken from https://hub.docker.com/r/caronc/apprise/ and https://github.com/caronc/apprise-api .

    # Variables to be configured by the user

    variables:
        - id: $$cap_apprise_version
          label: Apprise Version
          defaultValue: 'v0.7.0'
          description: Check out their docker page for the valid tags https://hub.docker.com/r/caronc/apprise/tags
          validRegex: /^([^\s^\/])+$/
    
# Docker-compose definition

services:
    
    $$cap_appname:
        image: caronc/apprise:$$cap_apprise_version
        restart: always
        volume:
            - $$cap_appname-data:/config
        caproverExtra:
            containerHttpPort: '8000'