# Caprover schema version
captainVersion: 4

# Parameters of the Caprover one-click app

caproverOneClickApp:

    # Title and description for one-click app gallery

    displayName: Vaultwarden (Bitwarden RS)
    description: Vaultwarden is a lightweight implementation of Bitwarden featuring all the essential core functionality
    
    # Only mark true if the docker-compose is the official one provided by the app developer, or if it's from a trusted source

    isOfficial: true

    # Onboarding instructions

    instructions:

        # Configuration page (user sets variables here)

        start: |-
            
            ![Vaultwarden Logo](https://nbygyyaygsxxesvjjcwa.supabase.co/storage/v1/object/public/public/bitwarden.png?t=2022-08-12T10%3A20%3A36.843Z)
            

            ðŸŒ [Vaultwarden website](https://github.com/dani-garcia/vaultwarden)
            ðŸ“˜ [Help & docs](https://vaultwarden.discourse.group/)
            ðŸ’» [Source code](https://github.com/dani-garcia/vaultwarden)

            **Vaultwarden** is an unofficial lightweight implementation of Bitwarden featuring all the essential core functionality.
            This is a copy of the official Caprover image.
            Enter your Vaultwarden configuration parameters and click on next. The app will be deployed for you.  It will take about 1-2 minutes for the process to finish.

            â—**If you like this app**, consider [donating](https://github.com/sponsors/dani-garcia) to support developers.
        
        # Success page

        end: >-
            âœ¨âœ¨ **Vaultwarden is deployed successfully**. 
            Wait for a couple minutes for it to set up, then access at [https://$$cap_appname.$$cap_root_domain](https://$$cap_appname.$$cap_root_domain) and enjoy! 
            IMPORTANT: It will take up to 2 minutes for Vaultwarden to be ready. Before that, you might see a 502 error page.
            ** For Vaultwarden to work as intended, you need to enable https, force https, and enable websockets in Caprover app settings**.
            If you added the admin password on setup, go to https://$$cap_appname.$$cap_root_domain/admin to finish configuration.
            
    # Link to app's documentation and Docker Hub

    documentation: Access docs at https://github.com/dani-garcia/vaultwarden . Docker image is taken from https://hub.docker.com/r/vaultwarden/server .

    # Variables to be configured by the user

    variables:
        - id: $$cap_bitwardenrs_version
          label: vaultwarden Version
          defaultValue: 1.21.0
          description: Check out their Docker page for the valid tags https://hub.docker.com/r/vaultwarden/server/tags
          validRegex: /^([^\s^\/])+$/
        - id: $$cap_register_enabled
          label: enabled open registration
          defaultValue: true
          description: If field is true, all visitors can create an account. If false, only the administrator can invite other users.
          validRegex: /^(true|false)$/
        - id: $$cap_admin_token
          label: admin password
          defaultValue:
          description: this password enables the admin zone on /admin. If you let this password empty, the admin interface will be disabled and it will be the best safety option.
    
# Docker-compose definition

services:
    $$cap_appname:
        image: vaultwarden/server:$$cap_bitwardenrs_version
        environment:
            DOMAIN: https://$$cap_appname.$$cap_root_domain
            WEBSOCKET_ENABLED: true
            SIGNUPS_ALLOWED: $$cap_register_enabled
            ADMIN_TOKEN: $$cap_admin_token
        ports:
            - 3012:3012
        volumes:
            - $$cap_appname-data:/data
        restart: unless-stopped