# Caprover schema version
captainVersion: 4

# Parameters of the Caprover one-click app

caproverOneClickApp:

    # Title and description for one-click app gallery

    displayName: Budibase
    description: Budibase is a platform that helps you build internal apps and automations. It also provides a no-code backend you can use with other apps.
    
    # Only mark true if the docker-compose is the official one provided by the app developer, or if it's from a trusted source

    isOfficial: true

    # Onboarding instructions

    instructions:

        # Configuration page (user sets variables here)

        start: |-
            
            ![Budibase Logo](https://nbygyyaygsxxesvjjcwa.supabase.co/storage/v1/object/public/public/budibase%20logo.png?t=2022-08-16T14%3A00%3A59.976Z)
            

            🌐 [Budibase website](https://www.budibase.com/)
            📘 [Help & docs](https://docs.budibase.com/docs)
            💻 [Source code](https://github.com/Budibase/budibase)

            **Budibase** is a platform that helps you build internal apps and automations. It also provides a no-code backend you can use with other apps.
            Enter your Budibase configuration parameters and click on next. The app will be deployed for you.  It will take about 1-2 minutes for the process to finish.

            ❗**If you like this app**, consider switching to a [SaaS version](https://budibase.com/pricing/) to support developers.
        
        # Success page

        end: >-
            ✨✨ **Budibase is deployed successfully**. 
            Wait for a couple minutes for it to set up, then access at [http://$$cap_appname.$$cap_root_domain](http://$$cap_appname.$$cap_root_domain) and enjoy! 
            IMPORTANT: It will take up to 2 minutes for Budibase to be ready. Before that, you might see a 502 error page.
            
    # Link to app's documentation and Docker Hub

    documentation: Access docs at https://docs.budibase.com/docs . Docker docs can be found at https://docs.budibase.com/docs/docker-compose .

    # Variables to be configured by the user

    variables:
        - id: '$$cap_jwt_secret'
          label: JWT Secret
          defaultValue: 'testsecret'
          description: JWT Secret. You should change this.
        - id: '$$cap_minio_access_key'
          label: MINIO Access Key
          defaultValue: 'budibase'
          description: MINIO Access Key. You should change this.
        - id: '$$cap_minio_secret_key'
          label: MINIO Secret Key
          defaultValue: 'budibase'
          description: MINIO Secret Key. You should change this.
        - id: '$$cap_couch_db_password'
          label: CouchDB Password
          defaultValue: 'budibase'
          description: CouchDB Password. You should change this.
        - id: '$$cap_couch_db_user'
          label: CouchDB User
          defaultValue: 'budibase'
          description: CouchDB User. You should change this.
        - id: '$$cap_redis_password'
          label: Redis Password
          defaultValue: 'budibase'
          description: Redis Password. You should change this.
        - id: '$$cap_internal_api_key'
          label: Budibase Internal API Key
          defaultValue: 'budibase'
          description: Budibase Internal API Key. You should change this.
    
# Docker-compose definition

version: "3"
services:
  budibase:
    restart: unless-stopped
    image: budibase/budibase:latest
    ports:
      - "8080:80"
    environment:
      JWT_SECRET: $$cap_jwt_secret
      MINIO_ACCESS_KEY: $$cap_minio_access_key
      MINIO_SECRET_KEY: $$cap_minio_secret_key
      REDIS_PASSWORD: $$cap_redis_password
      COUCHDB_USER: $$cap_couch_db_user
      COUCHDB_PASSWORD: $$cap_couch_db_password
      INTERNAL_API_KEY: $$cap_internal_api_key
    volumes:
      - budibasedata:/data
volumes:
  budibasedata:
    driver: local