captainVersion: 4
# Use postgres/example user/password credentials
version: '3.1'

volumes:
  database-data:

networks:
  stack:
    name: stack
    external: false

services:
  database:
    image: postgres
    restart: always
    volumes:
      - database-data:/var/lib/postgresql/data/
    networks:
      - stack

  calcom:
    build:
      context:
      args:
        - NEXT_PUBLIC_WEBAPP_URL=${NEXT_PUBLIC_WEBAPP_URL}
        - NEXT_PUBLIC_LICENSE_CONSENT=${NEXT_PUBLIC_LICENSE_CONSENT}
        - CALCOM_TELEMETRY_DISABLED=${CALCOM_TELEMETRY_DISABLED}
        - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
        - CALENDSO_ENCRYPTION_KEY=${CALENDSO_ENCRYPTION_KEY}
        - DATABASE_URL=${DATABASE_URL}
      network: stack
    restart: always
    networks:
      - stack
    environment:
        NEXT_PUBLIC_WEBAPP_URL: $$cap_next_public_webapp_url 
        NEXT_PUBLIC_APP_URL: $$cap_next_public_webapp_url 
        NEXT_PUBLIC_LICENSE_CONSENT: $$cap_next_public_license_consent 
        CALCOM_TELEMETRY_DISABLED: $$cap_calcom_telemetry_disabled 
        DATABASE_URL: srv-captain--postgresql://$$cap_postgres_user:$$cap_postgres_password@$$cap_database_host/$$cap_postgres_db
        NEXTAUTH_SECRET: $$cap_next_auth_secret 
        CALENDSO_ENCRYPTION_KEY: $$cap_calendso_encryption_key 
        NODE_OPTIONS: --max-old-space-size=4096
    caproverExtra:
            notExposeAsWebApp: true
            dockerfileLines:
                - FROM node:16 as builder
                - RUN git clone https://github.com/calcom/cal.com.git
                - WORKDIR /cal.com
                - RUN yarn install --frozen-lockfile
                - RUN yarn build
                - FROM node:16 as runner
                - WORKDIR /cal.com
                - ENV NODE_ENV production
                - RUN apt-get update 
                - RUN apt-get -y install netcat  
                - RUN rm -rf /var/lib/apt/lists/*
                - RUN npm install --global prisma
                - EXPOSE 3000
                - CMD ["/calcom/scripts/start.sh"]
    depends_on:
      - database
caproverOneClickApp:
    variables:
        - id: '$$cap_next_public_webapp_url'
          label: Web App URL
          defaultValue: 'http://localhost:3000'
          description: The URL of the public web app.
        - id: '$$cap_next_public_license_consent'
          label: Public License Consent
          defaultValue: 'agree'
          description: Set this value to "agree" if you agree to the license at https://github.com/calendso/calendso/blob/main/LICENSE
        - id: '$$cap_calcom_telemetry_disabled'
          label: Disable Cal.com Telemetry
          defaultValue: '1'
          description: Set this value to 1 if you don't want Cal.com to collect anonymous usage data to improve their services
        - id: '$$cap_next_auth_secret'
          label: Auth Secret
          defaultValue: $$cap_gen_random_hex(10)
          description: Authorization secret for the web app. Highly recommended that this value is unique
        - id: '$$cap_calendso_encryption_key'
          label: Cal.com Encryption Key
          defaultValue: $$cap_gen_random_hex(10)
          description: Encryption key used to encrypt CalDAV credentials. Must be a random string.
        - id: '$$cap_postgres_user'
          label: PostgreSQL User
          defaultValue: 'unicorn_user'
          description: User of the postgres database. You should change this.
        - id: '$$cap_postgres_password'
          label: PostgreSQL Password
          defaultValue: 'magical_password'
          description: Password of the postgres database. You should change this.
        - id: '$$cap_database_host'
          label: Database host
          defaultValue: 'database:5432'
          description: Database host. Usually you don't need to change this.
        - id: '$$cap_postgres_db'
          label: PostgreSQL database
          defaultValue: 'calendso'
          description: I have no idea. Better not touch this.
        
    instructions:
        start: |-
            Cal.com is an open-source Calendly alternative
        end: |-
            Cal.com has been successfully deployed!
    displayName: Cal.com
    isOfficial: true
    description: An open-source Calendly alternative
    documentation: See https://github.com/calcom/cal.com