# Caprover schema version
captainVersion: 4

# Parameters of the Caprover one-click app

caproverOneClickApp:

    # Title and description for one-click app gallery

    displayName: Changedetection.io
    description: Changedetection.io is a system for tracking changes on any website automatically.
    
    # Only mark true if the docker-compose is the official one provided by the app developer, or if it's from a trusted source

    isOfficial: true

    # Onboarding instructions

    instructions:

        # Configuration page (user sets variables here)

        start: |-
            
            ![Changedetection.io Logo](https://nbygyyaygsxxesvjjcwa.supabase.co/storage/v1/object/public/public/changedetection.png?t=2022-08-16T14%3A30%3A00.699Z)
            

            🌐 [Changedetection.io website](https://www.changedetection.io/)
            📘 [Help & docs](https://github.com/dgtlmoon/changedetection.io/wiki)
            💻 [Source code](https://github.com/dgtlmoon/changedetection.io/)

            **Changedetection.io** is a system for tracking changes on any website automatically.
            This is a copy of the official Caprover image.
            Enter your Changedetection.io configuration parameters and click on next. The app will be deployed for you.  It will take about 1-2 minutes for the process to finish.
            **Enable Basic Auth in Caprover settings** for this app to improve security.

            ❗**If you like this app**, consider [donating](https://github.com/dgtlmoon/changedetection.io#support-us) or switching to a [SaaS version](https://lemonade.changedetection.io/start) to support developers.
        
        # Success page

        end: >-
            ✨✨ **Changedetection.io is deployed successfully**. 
            Wait for a couple minutes for it to set up, then access at [http://$$cap_appname.$$cap_root_domain](http://$$cap_appname.$$cap_root_domain) and enjoy! 
            IMPORTANT: It will take up to 2 minutes for Changedetection.io to be ready. Before that, you might see a 502 error page.
            
    # Link to app's documentation and Docker Hub

    documentation: Access docs at https://github.com/dgtlmoon/changedetection.io/wiki .

    # Variables to be configured by the user

    variables:
        - id: $$cap_changedtc_version
          label: ChangeDetection.io version
          defaultValue: 0.39.3
          description: 'Check out their docker page for the list of versions (tags) https://hub.docker.com/r/dgtlmoon/changedetection.io/tags'
    
# Docker-compose definition
services:
    $$cap_appname:
        image: dgtlmoon/changedetection.io:$$cap_changedtc_version
        environment:
            BASE_URL: http://$$cap_appname.$$cap_root_domain
        volumes:
            - '$$cap_appname-data:/datastore'
        caproverExtra:
            containerHttpPort: '5000'