captainVersion: 4
caproverOneClickApp:
    displayName: PostHog (Work in progress v1)
    isOfficial: true
    description: An open-source analytics platform
    documentation: See https://posthog.com/docs
    variables:
        - id: $$cap_posthog_secret_key
          label: Random secret key
          defaultValue: $$cap_gen_random_hex(16)
        - id: $$cap_posthog_port
          label: The port that's used to deploy posthog
          defaultValue: 8000
    instructions:
        start: Posthog
        end: Posthog is deployed. Visit $$cap_appname.$$cap_root_domain to continue.
####################        
services:
    $$cap_appname-db:
        container_name: $$cap_appname-db
        environment:
            POSTGRES_DB: posthog
            POSTGRES_PASSWORD: posthog
            POSTGRES_USER: posthog
        image: postgres:13-alpine
        volumes:
            - $$cap_appname-postgres-data:/var/lib/postgresql/data
        caproverExtra:
            notExposeAsWebApp: 'true'
    $$cap_appname-redis:
        container_name: $$cap_appname-redis
        image: redis:6-alpine
        caproverExtra:
            notExposeAsWebApp: 'true'
    $$cap_appname-clickhouse:
        # KEEP CLICKHOUSE-SERVER VERSION IN SYNC WITH
        # https://github.com/PostHog/charts-clickhouse/blob/main/charts/posthog/templates/clickhouse_instance.yaml#L88
        image: yandex/clickhouse-server:21.11.11.1
        depends_on:
            - $$cap_appname-kafka
            - $$cap_appname-zookeeper
        ports:
            - '8123:8123'
            - '9000:9000'
            - '9440:9440'
            - '9009:9009'
        volumes:
            - /root/apps/posthog/ee/idl:/idl
            - /root/apps/posthog/docker/clickhouse/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
            - /root/apps/posthog/docker/clickhouse/config.xml:/etc/clickhouse-server/config.xml
            - /root/apps/posthog/docker/clickhouse/users.xml:/etc/clickhouse-server/users.xml
        caproverExtra:
            notExposeAsWebApp: 'true'
    $$cap_appname-zookeeper:
        image: wurstmeister/zookeeper
        caproverExtra:
            notExposeAsWebApp: 'true'
    $$cap_appname-kafka:
        image: bitnami/kafka:2.8.1-debian-10-r99
        depends_on:
            - $$cap_appname-zookeeper
        ports:
            - '9092:9092'
        environment:
            KAFKA_BROKER_ID: 1001
            KAFKA_CFG_RESERVED_BROKER_MAX_ID: 1001
            KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
            KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://srv-captain--$$cap_appname-kafka:9092
            KAFKA_CFG_ZOOKEEPER_CONNECT: srv-captain--$$cap_appname-zookeeper:2181
            ALLOW_PLAINTEXT_LISTENER: 'true'
        caproverExtra:
            notExposeAsWebApp: 'true'
    $$cap_appname:
        container_name: $$cap_appname-web
        depends_on:
            - $$cap_appname-db
            - $$cap_appname-redis
            - $$cap_appname-clickhouse
            - $$cap_appname-kafka
        environment:
            SITE_URL: https://$$cap_appname.$$cap_root_domain
            DATABASE_URL: postgres://posthog:posthog@srv-captain--$$cap_appname-db:5432/posthog
            REDIS_URL: redis://srv-captain--$$cap_appname-redis:6379/
            KAFKA_URL: 'kafka://srv-captain--$$cap_appname-kafka:9092'
            KAFKA_HOSTS: 'srv-captain--$$cap_appname-kafka:9092'
            CLICKHOUSE_HOST: 'srv-captain--$$cap_appname-clickhouse'
            CLICKHOUSE_DATABASE: 'posthog'
            CLICKHOUSE_SECURE: 'false'
            CLICKHOUSE_VERIFY: 'false'
            SECRET_KEY: $$cap_posthog_secret_key
            PGHOST: srv-captain--$$cap_appname-db
            PGUSER: posthog
            PGPASSWORD: posthog
            IS_BEHIND_PROXY: 'true'
        image: posthog/posthog:latest-release
        #links:
        #    - db:db
        #    - redis:redis
        #    - clickhouse:clickhouse
        #    - kafka:kafka
        ports:
            - $$cap_posthog_port:8000
        caproverExtra:
            containerHttpPort: '$$cap_posthog_port'
#volumes:
#    $$cap_appname-postgres-data:
#version: '3'